apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: selenium-salesforce-client
  labels:
    app: selenium-salesforce-client
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: [[ INSERT DOCKER NAME ]]
            image: [[ INSERT DOCKER IMAGE ]]
            imagePullPolicy: IfNotPresent         
          restartPolicy: OnFailure   